version: "3.9"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.0"
    environment:
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        - "discovery.type=single-node"
        - "xpack.security.enabled=true"  # Adds username and password.
        - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD} # Default user is 'elastic'.

    ports:
        - "9200:9200"

    volumes:
        - es_data:/usr/share/elasticsearch/data


  kibana:
    image: "docker.elastic.co/kibana/kibana:7.15.0"
    ports:
        - "5601:5601"

    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}

    depends_on:
      - elasticsearch


  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.15.0"
    command: [--strict.perms=false]
    user: root
    volumes:
        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - elasticsearch
      - kibana

    env_file:
      - .env

  app:
    build: .
    container_name: epilog
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        python3.10 emitter.py

    depends_on:
      - elasticsearch
      - kibana
      - filebeat


volumes:
    es_data:
