version: "3.9"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.0"
    environment:
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        - "discovery.type=single-node"
        - "xpack.security.enabled=true"  # Adds username and password.
        - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD} # Default user is 'elastic'.

    ports:
        - "9200:9200"
    volumes:
        - es_data:/usr/share/elasticsearch/data
    networks:
      - epi_net


  kibana:
    image: "docker.elastic.co/kibana/kibana:7.15.0"
    ports:
        - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - epi_net


  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.15.0"
    command: [--strict.perms=false]
    user: root
    volumes:
        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
      - kibana

    env_file:
      - .env
    networks:
      - epi_net

  app:
    build: .
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        ./scripts/wait_for.sh
        ./scripts/purge_logs.sh
        python3.10 -m epilog.emitter

    ports:
        - "8001:8001"

    depends_on:
      - elasticsearch
      - kibana
      - filebeat

    networks:
      - epi_net

    env_file:
      - .env

  caddy:
      image: caddy:2-alpine
      container_name: caddy
      env_file:
        - .env
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config

      networks:
        - epi_net



volumes:
  es_data:
  caddy_data:
  caddy_config:

networks:
  epi_net:
    driver: bridge
